(() => {
'use strict';
const DB='shicuo-mistakes-v1', API_SETTINGS='shicuo-ai-settings-v1', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const modules={'数学二':['高等数学','线性代数'],'英语二':['完形填空','阅读理解','新题型','翻译','写作'],'政治':['马克思主义基本原理','毛泽东思想和中国特色社会主义理论体系','中国近现代史纲要','思想道德与法治','时事政治'],'408':['数据结构','计算机组成原理','操作系统','计算机网络']};
let items=read(), subject='',module='',mode='home',activeId='',toastTimer;
function read(){try{return (JSON.parse(localStorage.getItem(DB))||[]).map(x=>({...x,sourceType:x.sourceType||(x.image?'photo':'paste'),sourceText:x.sourceText??(x.image?'':x.question||''),question:normalizeMathText(x.question),answer:normalizeMathText(x.answer),explanation:normalizeMathText(x.explanation)}))}catch{return[]}}
function save(){try{localStorage.setItem(DB,JSON.stringify(items));return true}catch{notice('浏览器空间不足，请导出备份或移除大图片');return false}}
const date=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const addDays=n=>{let d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(s){let t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2500)}
function aiSettings(){try{return {url:'https://api.agnes-ai.cn/v1',model:'agnes-3.0-flash',key:'',...JSON.parse(localStorage.getItem(API_SETTINGS)||'{}')}}catch{return {url:'https://api.agnes-ai.cn/v1',model:'agnes-3.0-flash',key:''}}}
function readTexGroup(text,start){if(text[start]!=='{')return null;let depth=0;for(let i=start;i<text.length;i++){if(text[i]==='{')depth++;else if(text[i]==='}'&&--depth===0)return{value:text.slice(start+1,i),end:i+1}}return null}
function normalizeMathText(value){let s=String(value??'');for(let pass=0;pass<20;pass++){let changed=false,re=/\\(?:dfrac|tfrac|frac)\s*\{/g,m;while((m=re.exec(s))){let a=readTexGroup(s,m.index+m[0].lastIndexOf('{'));if(!a)continue;let j=a.end;while(/\s/.test(s[j]||''))j++;let b=readTexGroup(s,j);if(!b)continue;s=s.slice(0,m.index)+`(${a.value})/(${b.value})`+s.slice(b.end);changed=true;break}if(!changed)break}s=s.replace(/\\sqrt\s*\{([^{}]*)\}/g,'√($1)').replace(/\\(?:text|mathrm|mathbf|mathit)\s*\{([^{}]*)\}/g,'$1').replace(/\\(?:left|right)\b/g,'').replace(/\\(?:begin|end)\s*\{[^{}]*\}/g,'');const symbols={alpha:'α',beta:'β',gamma:'γ',delta:'δ',epsilon:'ε',theta:'θ',lambda:'λ',mu:'μ',pi:'π',sigma:'σ',omega:'ω',partial:'∂',nabla:'∇',int:'∫',sum:'∑',prod:'∏',infty:'∞',cdot:'·',times:'×',pm:'±',leq:'≤',le:'≤',geq:'≥',ge:'≥',neq:'≠',approx:'≈',equiv:'≡',to:'→',rightarrow:'→',Rightarrow:'⇒',leftarrow:'←',in:'∈',notin:'∉',cup:'∪',cap:'∩',therefore:'∴',because:'∵',quad:' ',qquad:' '};return s.replace(/\\([A-Za-z]+)\b/g,(m,k)=>symbols[k]??k).replace(/\\(?:,|;|!|:|\s)/g,' ').replace(/\\([{}])/g,'$1').replace(/\^\{([^{}]*)\}/g,'^($1)').replace(/_\{([^{}]*)\}/g,'_($1)').replace(/\s+([,.;，。；])/g,'$1')}
function sourceKind(x){return x.sourceType||(x.image?'photo':'paste')}
function originalText(x){return x.sourceText??(sourceKind(x)==='paste'?x.question||'':'')}

function setNav(id){$$('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.id===id))}
function home(){mode='home';subject='';module='';$('#subjectsHome').hidden=false;$('#libraryView').hidden=true;$('#newBtn').hidden=true;$('#pageTitle').textContent='今天，先从哪一科开始？';$('#pageSubtitle').textContent='按科目整理错题，让每次复习都有方向。';$('#crumb').textContent='拾错　/　科目首页';setNav('navHome');location.hash='home'}
function library(s='',m=''){mode=s?'subject':'library';subject=s;module=m;$('#subjectsHome').hidden=true;$('#libraryView').hidden=false;$('#newBtn').hidden=false;$('#subject').value=s;$('#search').value='';$('#knowledgeFilter').value='';$('#status').value='';$('#sort').value='new';$('#crumb').textContent='拾错　/　'+(m?`${s}　/　${m}`:s||'错题总库');$('#pageTitle').textContent=s?`${m||s}错题`:'错题总库';$('#pageSubtitle').textContent=s?'记录会自动归入当前科目，复习和整理都从这里继续。':'汇总所有科目，按科目、知识点和复习状态检索。';$('#scopeNote').textContent=m?`${s} · ${m}`:s||'全部科目';setNav(s?'navHome':'navLibrary');render();location.hash=s?'subject':'library'}
function avg(a){return a.reduce((n,x)=>n+(x.mastery||1),0)/a.length}
function render(){let due=items.filter(x=>x.nextReview<=date()).length,weak=items.filter(x=>(x.mastery||1)<3).length,done=items.filter(x=>(x.mastery||1)>=4).length;
if($('#dueCount'))$('#dueCount').textContent=due;$('#dueBanner').hidden=!due;$('#dueTitle').textContent=due?`今天有 ${due} 道错题待复习`:'今日复习已完成';$('#dueText').textContent=due?'回忆、判断，再安排下一次复习。':'保持节奏，新的复习会按计划出现。';
$('#stats').innerHTML=`<div class="stat"><span>累计错题</span><strong>${items.length}<em>道</em></strong></div><div class="stat"><span>今日待复习</span><strong>${due}<em>道</em></strong></div><div class="stat"><span>需要加强</span><strong>${weak}<em>道</em></strong></div><div class="stat"><span>已掌握</span><strong>${done}<em>道</em></strong></div>`;
let sel=$('#module').value,sub=$('#subject').value,opts=sub?modules[sub]||[]:[...new Set(items.map(x=>x.module).filter(Boolean))].sort();$('#module').innerHTML='<option value="">所有模块</option>'+opts.map(x=>`<option>${esc(x)}</option>`).join('');$('#module').value=opts.includes(module)?module:(opts.includes(sel)?sel:'');
let tags=[...new Set(items.flatMap(x=>x.tags||[]))].sort(),tag=$('#tagFilter').value;$('#tagFilter').innerHTML='<option value="">所有标签</option>'+tags.map(x=>`<option>${esc(x)}</option>`).join('');if(tags.includes(tag))$('#tagFilter').value=tag;
let q=$('#search').value.toLowerCase().trim(),k=$('#knowledgeFilter').value.toLowerCase().trim(),st=$('#status').value,md=$('#module').value,tg=$('#tagFilter').value;
let a=items.filter(x=>(!q||[x.question,x.knowledge,x.module,x.explanation,(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(q))&&(!sub||x.subject===sub)&&(!md||x.module===md)&&(!tg||(x.tags||[]).includes(tg))&&(!k||(x.knowledge||'').toLowerCase().includes(k))&&(st!=='due'||x.nextReview<=date())&&(st!=='weak'||(x.mastery||1)<3)&&(st!=='mastered'||(x.mastery||1)>=4));
if($('#sort').value==='due')a.sort((x,y)=>(x.nextReview||'').localeCompare(y.nextReview||''));else if($('#sort').value==='weak')a.sort((x,y)=>(x.mastery||1)-(y.mastery||1));else a.sort((x,y)=>y.createdAt-x.createdAt);
$('#resultCount').textContent=`${a.length} 道`;
$('#list').innerHTML=a.length?a.map(card).join(''):`<div class="empty"><b>${items.length?'没有找到符合条件的错题':'这里还没有错题'}</b>${items.length?'试试调整筛选条件。':'进入科目后拍照或粘贴题目，记录就会出现在这里。'}${!items.length?'<br><br><button class="primary" data-new>记录第一道错题</button>':''}</div>`;
let map={};items.forEach(x=>(x.knowledge||'').split(/[,，、]/).map(z=>z.trim()).filter(Boolean).forEach(z=>(map[z]??=[]).push(x)));let pairs=Object.entries(map).sort((x,y)=>avg(x[1])-avg(y[1])).slice(0,10);$('#knowledgeMap').innerHTML=pairs.length?pairs.map(([name,xs])=>{let n=Math.round(avg(xs)/5*100);return `<div class="knowledge-item"><b>${esc(name)}</b><span>${xs.length} 道 · ${n<45?'需加强':n<75?'继续巩固':'较稳固'}</span><div class="bar"><i style="width:${n}%"></i></div></div>`}).join(''):'<div class="empty" style="grid-column:1/-1;padding:24px">错题补充知识点后，这里会显示掌握概览。</div>';
if(mode!=='home')$('#libraryTitle').innerHTML=`${esc(subject?(module||subject)+'错题':'错题总库')} <span id="resultCount">${a.length} 道</span>`}
function card(x){let m=x.mastery||1,photo=sourceKind(x)==='photo',original=photo?(x.image?`<img class="card-original-image" src="${x.image}" alt="错题原图">`:'<div class="card-source-empty">尚未添加题目照片</div>'):`<div class="card-source-text">${esc(normalizeMathText(originalText(x))||'尚未填写题目内容')}</div>`;return `<article class="mistake-card"><div><div class="card-meta"><span class="subject-pill">${esc(x.subject)}</span><span>${new Date(x.createdAt).toLocaleDateString('zh-CN')}</span>${x.nextReview<=date()?'<span class="tag">待复习</span>':''}</div><div class="card-original">${original}</div></div><div class="card-right"><span class="mastery ${m>=4?'done':m<=2?'low':''}">${m>=4?'已掌握':m<=2?'需加强':'复习中'} · ${m}/5</span><div class="card-actions"><button data-review="${x.id}">复习</button><button data-edit="${x.id}">详情与分类</button></div></div></article>`}
function newRecord(){if(!subject){notice('先从首页选择一科');home();return}$('#recordScope').textContent=module?`${subject} · ${module}`:subject;$('#recordChoice').hidden=false;$('#pasteView').hidden=true;$('#recordProgress').hidden=true;$('#pasteQuestion').value='';$('#captureInput').value='';$('#uploadInput').value='';$('#recordDialog').showModal()}
$('#newBtn').onclick=newRecord;$('#navHome').onclick=e=>{e.preventDefault();home()};$('#brandHome').onclick=e=>{e.preventDefault();home()};$('#navLibrary').onclick=e=>{e.preventDefault();library()};$('#navInsights').onclick=e=>{e.preventDefault();if(mode==='home')library();setTimeout(()=>$('#insights').scrollIntoView({behavior:'smooth'}),0)};$('#openAllLibrary').onclick=()=>library();
document.addEventListener('click',e=>{let c=e.target.closest('[data-close]');if(c){let d=$('#'+c.dataset.close);if(d?.open)d.close()}if(e.target.closest('[data-new]'))newRecord();let s=e.target.closest('[data-open-subject]');if(s){library(s.dataset.openSubject,s.dataset.openModule||'');$('#library').scrollIntoView({behavior:'smooth'})}let ed=e.target.closest('[data-edit]');if(ed)detail(items.find(x=>x.id===ed.dataset.edit),false);let rv=e.target.closest('[data-review]');if(rv)review(rv.dataset.review)});
['#module','#subject','#status','#tagFilter','#sort'].forEach(s=>$(s).addEventListener('change',()=>{if(s==='#subject')subject=$('#subject').value;render()}));['#search','#knowledgeFilter'].forEach(s=>$(s).addEventListener('input',render));
$('#choosePhoto').onclick=()=>$('#captureInput').click();$('#chooseUpload').onclick=()=>$('#uploadInput').click();async function handleImageInput(e){let f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){notice('请选择图片文件');e.target.value='';return}$('#recordChoice').hidden=true;$('#recordProgress').hidden=false;try{let image=await compress(f);create('',image,'photo')}catch{notice('读取图片失败，请重试')}e.target.value=''}$('#captureInput').onchange=handleImageInput;$('#uploadInput').onchange=handleImageInput;
$('#choosePaste').onclick=()=>{$('#recordChoice').hidden=true;$('#pasteView').hidden=false;$('#pasteQuestion').focus()};$$('[data-back-record]').forEach(b=>b.onclick=()=>{$('#pasteView').hidden=true;$('#recordChoice').hidden=false});$('#savePasted').onclick=()=>{let q=$('#pasteQuestion').value.trim();if(!q){notice('先粘贴题目内容');return}create(q,'','paste')};
function compress(file){return new Promise((ok,no)=>{let im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{let z=Math.min(1,1500/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*z);c.height=Math.round(im.height*z);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);ok(c.toDataURL('image/jpeg',.76))};im.onerror=()=>{URL.revokeObjectURL(u);no()};im.src=u})}
function create(q,image,kind){let x={id:crypto.randomUUID(),sourceType:kind||(image?'photo':'paste'),sourceText:q,question:q,subject,module,knowledge:'',type:'',difficulty:'',cause:'',myAnswer:'',answer:'',explanation:'',tags:[],createdAt:Date.now(),mastery:1,reviews:0,nextReview:date(),lastReview:'',image};items.unshift(x);if(!save())return;$('#recordDialog').close();render();detail(x,true);notice('错题已保存')}
function detail(x,analyze){if(!x)return;activeId=x.id;let f=$('#detailForm');f.reset();for(let k of ['id','question','subject','module','knowledge','type','difficulty','cause','myAnswer','answer','explanation','tags'])if(f.elements[k])f.elements[k].value=k==='id'?x.id:k==='tags'?(x.tags||[]).join('，'):['question','answer','myAnswer','explanation'].includes(k)?normalizeMathText(x[k]??''):x[k]??'';let photo=sourceKind(x)==='photo';$('#detailImage').innerHTML=photo?(x.image?`<div class="source-preview-label">记录时的照片</div><img class="detail-image" src="${x.image}" alt="错题原图">`:'<div class="card-source-empty">尚未添加题目照片</div>'):`<div class="source-preview-label">记录时粘贴的原文</div><div class="source-text-preview">${esc(normalizeMathText(originalText(x))||'尚未填写题目内容')}</div>`;$('#detailMessage').textContent=analyze?'题目已保存，正在分析原始内容。':'可在此补充或修改分类、答案与复盘。';$('#detailDialog').showModal();if(analyze)analyse(x.id)}
$('#detailForm').onsubmit=e=>{e.preventDefault();let f=e.currentTarget,x=items.find(z=>z.id===activeId);for(let k of ['question','subject','module','knowledge','type','difficulty','cause','myAnswer','answer','explanation'])x[k]=f.elements[k].value.trim();x.tags=f.elements.tags.value.split(/[,，、]/).map(z=>z.trim()).filter(Boolean);if(save()){render();$('#detailDialog').close();notice('错题详情已保存')}};
$('#deleteBtn').onclick=()=>{if(!confirm('确定删除这道错题吗？此操作无法撤销。'))return;items=items.filter(x=>x.id!==activeId);save();$('#detailDialog').close();render();notice('错题已删除')};
async function analyse(id){let x=items.find(z=>z.id===id),settings=aiSettings();$('#reanalyze').disabled=true;if(!settings.key){$('#detailMessage').textContent='先在“AI 服务”设置中填写 Agnes API 密钥。题目已保存，可手动补充分类。';$('#reanalyze').disabled=false;return}$('#detailMessage').textContent='正在让 Agnes 模型识别题目并整理知识点、题型和难度…';try{let content=[{type:'text',text:`科目（已由学习者选定，请勿修改）：${x.subject}\n模块（如已选定请优先保留）：${x.module||''}\n题目文字：${sourceKind(x)==='paste'?originalText(x):'请仅根据附图识别题目，不要使用先前可能有误的识别文字。'}\n请识别题目，整理知识点、题型、难度、错因、答案和清晰简短的解析。数学内容必须使用 Unicode 符号（如 α、∂、∫、√、≤），分数写成 (分子)/(分母)，不要输出任何 LaTeX 命令或反斜杠格式。`}];if(x.image)content.push({type:'image_url',image_url:{url:x.image}});let endpoint=settings.url.replace(/\/+$/,'');if(!endpoint.endsWith('/chat/completions'))endpoint+='/chat/completions';let r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${settings.key}`},body:JSON.stringify({model:settings.model,temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:'你是严谨的中国考研错题整理助手。只根据给定题目作答，不臆造题目条件。所有公式使用 Unicode 数学符号，分数写成 (分子)/(分母)，严禁输出 LaTeX 命令、反斜杠和未渲染公式。只返回 JSON 对象，字段：question(识别出的完整题干), module(简短章节), knowledge(知识点，可多个，用中文顿号分隔), type(题型), difficulty(1基础/2中等/3较难), cause(错因，若无作答信息则留空), answer(若无法判断留空), explanation(中文解析), tags(字符串数组)。题目所属科目已由用户选择，不要改写。'},{role:'user',content}]})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||d.message||`分析失败（${r.status}）`);let raw=d.choices?.[0]?.message?.content;if(typeof raw!=='string')throw Error('AI 返回内容无法解析');raw=raw.replace(/^```(?:json)?\s*|\s*```$/gi,'').trim();d=JSON.parse(raw);for(let k of ['question','module','knowledge','type','difficulty','cause','answer','explanation'])if(d[k]!==undefined&&d[k]!==null&&d[k]!=='')x[k]=normalizeMathText(d[k]);if(Array.isArray(d.tags))x.tags=d.tags.map(String);save();for(let k of ['question','module','knowledge','type','difficulty','cause','answer','explanation'])if($('#detailForm').elements[k])$('#detailForm').elements[k].value=x[k]||'';$('#detailForm').elements.tags.value=(x.tags||[]).join('，');$('#detailMessage').textContent='AI 已整理完成，请核对题目识别、知识点和答案后保存。';render();notice('AI 整理完成，请核对后保存')}catch(err){$('#detailMessage').textContent=`AI 暂未完成：${err.message}。题目已保存，可在下方手动补充。`;notice('题目已保存，可手动补充分类')}finally{$('#reanalyze').disabled=false}}
$('#reanalyze').onclick=()=>analyse(activeId);
$('#settingsBtn').onclick=()=>{$('#settingsDialog').showModal();let s=aiSettings();$('#aiBackendUrl').value=s.url;$('#aiModel').value=s.model;$('#aiAccessToken').value=s.key;checkAiStatus()};
async function checkAiStatus(){let b=$('#serviceState'),s=aiSettings();b.innerHTML=s.key?'<span class="state-dot connected"></span><b>本设备已配置</b><span>分析时直接连接 Agnes API</span>':'<span class="state-dot disconnected"></span><b>请填写 API 密钥</b><span>保存后即可在此设备使用 AI</span>'}
$('#saveAiSettings').onclick=()=>{let url=$('#aiBackendUrl').value.trim().replace(/\/+$/,''),model=$('#aiModel').value.trim(),key=$('#aiAccessToken').value.trim();if(!/^https:\/\//i.test(url)||!model){notice('请检查 API 地址和模型名称');return}localStorage.setItem(API_SETTINGS,JSON.stringify({url,model,key}));checkAiStatus();notice('AI 设置已保存在本设备')};
$('#reviewDue').onclick=()=>{let x=items.filter(z=>z.nextReview<=date()).sort((a,b)=>a.nextReview.localeCompare(b.nextReview))[0];if(x)review(x.id)};
function review(id){let x=items.find(z=>z.id===id),shown=false;if(!x)return;let photo=sourceKind(x)==='photo',source=photo?(x.image?`<img class="review-source-image" src="${x.image}" alt="待复习题目照片">`:'尚未添加题目照片'):esc(normalizeMathText(originalText(x)||'尚未填写题目内容'));$('#reviewBody').innerHTML=`<div class="card-meta"><span class="subject-pill">${esc(x.subject)}</span></div><div class="review-question">${source}</div><div id="answerReveal" hidden class="review-answer"><b>正确答案</b><br>${esc(x.answer||'未填写')}<br><br><b>我的答案</b><br>${esc(x.myAnswer||'未填写')}${x.explanation?`<br><br><b>解析</b><br>${esc(x.explanation)}`:''}</div>`;let a=$('#reviewActions');a.innerHTML='<button class="primary" id="revealAnswer">显示答案</button><button class="secondary" data-close="reviewDialog">稍后复习</button>';$('#revealAnswer').onclick=()=>{if(shown)return;shown=true;$('#answerReveal').hidden=false;a.innerHTML='<button class="delete" data-grade="0">没想起来</button><button class="secondary" data-grade="2">有点模糊</button><button class="primary" data-grade="4">记住了</button>'};a.onclick=e=>{let b=e.target.closest('[data-grade]');if(!b)return;let g=+b.dataset.grade,m=x.mastery||1,days=[1,2,4,7,14,30,60];x.mastery=g===0?Math.max(1,m-1):g===2?Math.min(4,m):Math.min(5,m+1);x.reviews=(x.reviews||0)+1;x.lastReview=date();x.nextReview=addDays(g===0?1:days[Math.min(5,x.mastery)]);save();$('#reviewDialog').close();render();notice(`已记录，下次复习：${x.nextReview}`)};$('#reviewDialog').showModal()}
$('#exportBtn').onclick=()=>{let b=new Blob([JSON.stringify({version:1,items},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`拾错备份-${date()}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{let d=JSON.parse(await e.target.files[0].text()),inc=Array.isArray(d)?d:d.items;if(!Array.isArray(inc))throw 0;if(!confirm(`导入 ${inc.length} 道错题？同 ID 的记录将由备份覆盖。`))return;let m=new Map(items.map(x=>[x.id,x]));inc.forEach(x=>{if(x.id&&x.subject)m.set(x.id,x)});items=[...m.values()];if(save()){render();notice('导入完成')}}catch{notice('备份文件格式不正确')}e.target.value=''};
async function status(){let s=aiSettings();$('#settingsBtn').textContent=s.key?'AI 已配置':'配置 AI 密钥'}
$('#recordDialog').addEventListener('close',()=>{$('#captureInput').value='';$('#uploadInput').value=''});render();status();if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
